App.open("Yousician Launcher.app")
wait("home.png", 60)
App.focus("Yousician")
click("settings.png")
wait("guitar.png")
click("guitar.png")
wait("challenges.png")
click("challenges.png")
wait("history.png")
click("history.png")
wait(1)
click(Location(700, 400))
wait(1)
print(Region(100,100,1266,100).text())
App.focus("Firefox")
