App.open("Yousician Launcher.app")
App.focus("Yousician")
click("settings.png")
wait(1)
click("guitar.png")
wait(1)
click("challenges.png")
wait(1)
click("history.png")
wait(1)
moveTo(Location(700, 400))
wheel(WHEEL_UP, 100)
print(Region(0,0,1366,768).text())